//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHTH.Database.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MHTHEntities : DbContext
    {
        public MHTHEntities()
            : base("name=MHTHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Monster> Monsters { get; set; }
        public virtual DbSet<QuestTemplate> QuestTemplates { get; set; }
        public virtual DbSet<QuestTemplateName> QuestTemplateNames { get; set; }
        public virtual DbSet<QuestTemplateLore> QuestTemplateLores { get; set; }
        public virtual DbSet<QuestTemplateClient> QuestTemplateClients { get; set; }
    }
}
