//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHTH.Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal CR { get; set; }
        public Nullable<int> BaseMonsterId { get; set; }
    }
}
