//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHTH.Database.Database
{
    using System;
    
    public enum QuestType : int
    {
        Gathering = 1,
        Hunting = 2,
        Capture = 3
    }
}
