//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHTH.Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestTemplate
    {
        public int Id { get; set; }
        public int QuestTemplateNameId { get; set; }
        public int QuestTemplateLoreId { get; set; }
        public int QuestTemplateClientId { get; set; }
        public QuestType QuestTypeId { get; set; }
        public Nullable<int> MonsterId { get; set; }
    
        public virtual QuestTemplateName QuestTemplateName { get; set; }
        public virtual QuestTemplateLore QuestTemplateLore { get; set; }
        public virtual QuestTemplateClient QuestTemplateClient { get; set; }
        public virtual Monster Monster { get; set; }
    }
}
